spin_version = "1"
authors = ["Murdho Savila <murdho@murdho.com>"]
description = "Listens to radio stations and notes down what is playing"
name = "traccumulator"
trigger = { type = "http", base = "/" }
version = "0.2.0"

[[component]]
id = "raadio-tallinn"
source = "raadio_tallinn/target/wasm32-wasi/release/raadio_tallinn.wasm"
allowed_http_hosts = ["https://raadiotallinn.err.ee"]
[component.trigger]
route = "/raadio-tallinn"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "raadio_tallinn"
[component.config]
current_track_api_url = "https://raadiotallinn.err.ee/api/rds/getForChannel?channel=raadiotallinn"

[[component]]
id = "groove-fm"
source = "supla_fi/target/wasm32-wasi/release/supla_fi.wasm"
allowed_http_hosts = ["https://supla-playlist.nm-services.nelonenmedia.fi"]
[component.trigger]
route = "/groove-fm"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "supla_fi"
[component.config]
playlist_api_url = "https://supla-playlist.nm-services.nelonenmedia.fi/playlist"
channel_id = "70"

[[component]]
id = "loop"
source = "supla_fi/target/wasm32-wasi/release/supla_fi.wasm"
allowed_http_hosts = ["https://supla-playlist.nm-services.nelonenmedia.fi"]
[component.trigger]
route = "/loop"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "supla_fi"
[component.config]
playlist_api_url = "https://supla-playlist.nm-services.nelonenmedia.fi/playlist"
channel_id = "54"
